### ISSUE TITLE
 API endpoint for web

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#174]
## User details

Additional fields as per [wireframe](https://www.figma.com/file/ke4oNCw67LgzvubDRJs97C/Ellandi-Prototype-V1.0?node-id=16%3A839)
* ~~Work location `location`~~
* Business Unit: `business_unit`

## Grade 
https://trello.com/c/muBBNtYK/14-grade

Support for :
*  `PATCH grade_other` field
*  `GET grade_other` field

##  **Profession**

* Support for `PATCH  profession_other` endpoint
* `GET /professions/` also returns "Other"
```lang-js
  {
    "name": "Other"
  }
```

### Request
```
Request URL: https://ellandi-api-develop.london.cloudapps.digital/users/d01e7240-330d-47fe-bbb0-d3cb35c14db4/
Request Method: PATCH
payload:  profession: ["Policy Profession"]
```

###  Response
```lang-js
{"profession":["Invalid hyperlink - No URL match."]}
```

## Function
https://trello.com/c/nINURaE6/15-function

* Api endpoint for list of functions  `GET /functions/`
* Api endpoint update for `PATCH /users/{id}/`  with `function` value
* Api endpoint update for `PATCH /users/{id}/`  with `function_other` value

## Contact Preference
https://trello.com/c/isztBWH4/25-contact-preference

Support for setting on endpoint - `PATCH /users/{id}/`
* `{ "contact_preference": "String" }`

## Contract type

* Api endpoint update for PATCH /users/{id}/ with `contract_type_other` value

## Language

* Support for setting on endpoint - `PATCH /users/{id}/`.  
*  Content updates: https://github.com/i-dot-ai/ellandi/issues/163

Structure example:
```lang-js
"languages": [
    {
        "language": "Hindi",
         "Speaking": "Proficient",
         "Writing": "Basic"
    },
    {
        "language": "English",
        "Speaking": "Basic",
        "Writing": "Basic"
    }
]
```

## Skills endpoint

* Support for setting on endpoint - `PATCH /users/{id}/`. Format as:
```lang-js
{skills: [{"name": "project management", "level": "blah"},{"name": "doing stuff", "level": "blah blah"}]}
```

## Add "Other" to response

Update the existing list returned in the response from Professions and Functions to contain "Other" 

**type** 
`GET`
**endpoints**
`/professions/` 
`/functions/`

**Comment by nmenezes0** [comment]
The following are now complete:
- User details
- Grade
- Function
- Contact preference (but a Boolean field)
- Contract type
- Add others to response

Still to do:
- All the profession stuff
- Languages
- Skills

**Comment by nmenezes0** [comment]
Professions changes now complete - all that's left is languages and skills.

**Comment by rottitime** [comment]
@Singletoned @nmenezes0 For languages is it possible we could have he following format please?

```lang-js
//PATCH: /users/{id}/
//GET: /me

{
  ...
  "languages": [
    {
      "language": "Other",
      "speaking": "Basic",
      "writing": "Independent"
    },
    {
      "language": "Russian",
      "speaking": "Basic",
      "writing": "Basic"
    }
  ]
}
