### ISSUE TITLE
Web: Docker optimise build process

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#381]
To optimise docker build for web process. Currently it is taking far too long.

## Utilise package-lock.json file

Use `npm ci` instead of `npm i`

## Migrate Typescript as a prod dependency

Investigate if this should move and implement

## Set `NODE_ENV` as production

Investigate whether we need to vary NODE_ENV? Can it be hardcoded to PRODUCTION in the docker image?

**Comment by Singletoned** [comment]
Can we also investigate whether we need to vary `NODE_ENV`?  Can it be hardcoded to `PRODUCTION` in the docker image?

**Comment by rottitime** [comment]
Closing as remaining work separated into #905
