### ISSUE TITLE
API: Bug: Unable to login with capital letter in 'email'

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#384]
After successfully registering a with a email containing a capital letter. For example

```lang-js
// POST /register/
{
    "email": "CAapital11@test.com",
    "password": "CAapital11@test.com",
    "emailConfirm": "CAapital11@test.com",
    "passwordConfirm": "CAapital11@test.com"
}
```

I am now unable to login with the same email:

<img width="275" alt="Screenshot 2022-08-25 at 14 02 27" src="https://user-images.githubusercontent.com/1698584/186671927-4dea050f-c3f5-4e9a-b379-0313210a5376.png">

**Comment by Singletoned** [comment]
You need to lower them before you submit
