### ISSUE TITLE
API: Updates for Learning

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#511]
Endpoint: `GET /me/learnings/` 

Can you either: update or add a new field to return the text for `types` to align with the content used across the website. e.g. "_Work_" should be returned as "_On the  job_" as per:

![Screenshot 2022-09-23 at 11 44 59](https://user-images.githubusercontent.com/1698584/191944729-f68e1546-d089-48bb-b909-46bb6368ec45.png)

**Comment by rottitime** [comment]
@Singletoned @nmenezes0 Can you confirm this change will be ok please?

**Comment by nmenezes0** [comment]
> @Singletoned @nmenezes0 Can you confirm this change will be ok please?

Yeah, that's fine
