### ISSUE TITLE
Static build: All urls render homepage

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#523]
## Steps

1. Go to  directly to: http://localhost:8002/signin

## Expected 

- Url shows as http://localhost:8002/signin/
- Signin page shows
![Screenshot 2022-09-26 at 16 55 30](https://user-images.githubusercontent.com/1698584/192323955-168d9ceb-d0f5-48a6-9d9e-fa559cd977bf.png)

## Actual

- Shows homepage content instead

![Screenshot 2022-09-26 at 16 57 14](https://user-images.githubusercontent.com/1698584/192324257-980d34b7-4f1d-419c-a245-f92d4bb60972.png)

### Request

```
Request URL: http://localhost:8002/signin/
Request Method: GET
Status Code: 200 OK
Remote Address: [::1]:8002
```

### Response
![Screenshot 2022-09-26 at 16 58 55](https://user-images.githubusercontent.com/1698584/192324604-2956683d-bce9-4cee-8c77-42c1d58a0d1f.png)

**Comment by rickyp72** [comment]
It might be related to the STATIC_ROOT configuration in settings_base.py - i'm just trying to understand how this works

**Comment by rottitime** [comment]
I have downloaded the actual `/staticfiles/` folder itself from the `ellandi_ellandi_1` container. 

I ran this folder against a basic http-server
```
http-server ./public/static/staticfiles -p 3002
```

All pages load correctly after refresh 
![Screenshot 2022-09-27 at 09 15 36](https://user-images.githubusercontent.com/1698584/192471987-fcb16a69-2cc8-4810-bf50-10c754b60e49.png)

The request differs on both `http-server` for signin:
```
Request URL: http://localhost:8002/register/
Request Method: GET
Status Code: 200 OK
Remote Address: [::1]:8002
Referrer Policy: same-origin
```

**Comment by rottitime** [comment]
Second test;

I have logged into the `ellandi_ellandi_1` container and created the following file in `/staticfiles/hello/index.html`

```
<p>Hello world</p>
```

No javascript or react routing. The same bug exists
