### ISSUE TITLE
Develop env: Enable emails on forgotten password

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#552]
This ticket is identical to #417 except for develop environment.

Can you enable email sending for the develop environment. Currently emails are not sent out 

## Steps
1. register https://ellandi-web-develop.london.cloudapps.digital/register/
2. reset password: https://ellandi-develop.london.cloudapps.digital/signin/forgotten-password/

**Comment by rickyp72** [comment]
@rottitime currently forgotten passwords works with https://ellandi-web-demo.london.cloudapps.digital/signin/forgotten-password/ but not with the static url that you posted above. - I will get it working with the new system as well but you can use the `web` url if you need it now

**Comment by rottitime** [comment]
@rickyp72 sorry I need this for develop not demo. I realised I mixed up the requirements a bit

**Comment by rickyp72** [comment]
Hi @rottitime this has been activated in `develop` now
