### ISSUE TITLE
Staging: Email notification link correction

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#568]
Email notifications have the wrong link. We will be encouraging Product owners to use static build but email notifications point to web instead.

Replace email notification urls:
`https://ellandi-web-staging.london.cloudapps.digital/signin/forgotten-password/reset?code=bcrqrv-8208e3779ee5304de44b75d021fa9dc5&user_id=472fdf1b-ccc3-4c5f-bae2-7b25a1be6d51`

with 
`https://ellandi-staging.london.cloudapps.digital/signin/forgotten-password/reset?code=bcrqrv-8208e3779ee5304de44b75d021fa9dc5&user_id=472fdf1b-ccc3-4c5f-bae2-7b25a1be6d51`

![Screen Shot 2022-10-04 at 13 03 53](https://user-images.githubusercontent.com/1698584/193815662-85a01ca3-8422-4006-9438-8826aac1381f.png)

---

## Steps

1. Register: https://ellandi-staging.london.cloudapps.digital/register/ 
2. Reset your password https://ellandi-staging.london.cloudapps.digital/signin/forgotten-password/
3. Check your email inbox

**Comment by nmenezes0** [comment]
I think this one is done.
