### ISSUE TITLE
Frontend: Errors on adding learning records

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#663]
Only recently started getting errors on below.

#### Request 
**Endpoint**: `PATCH /api/me/learning-formal/`
**Payload**: 
```
[
  {
    "name": "some record",
    "duration_minutes": 2250,
    "cost_pounds": 1,
    "cost_unknown": null,
    "date_completed": "2022-10-04"
  }
]
```

#### Response 
```lang-js
//400 Bad Request
[{"cost_unknown":["This field may not be null."]}]
```
![Screenshot 2022-10-19 at 11 38 21](https://user-images.githubusercontent.com/1698584/196668901-e08f0bbe-ae08-4eb4-9f27-04b7795dd7ce.png)

## API 'learning-on-the-job' and 'learning-social'

The form on web does not provide cost fields. 

`PATCH /api/me/learning-on-the-job/`
`PATCH /api/me/learning-social/`
Payload
```
[
  {
    "name": "Some record",
    "duration_minutes": 450,
    "cost_pounds": null,
    "cost_unknown": null,
    "date_completed": "2022-10-05"
  }
]
```

#### Response
```
[
  {
    "cost_pounds": [
      "This field may not be null."
    ],
    "cost_unknown": [
      "This field may not be null."
    ]
  }
]
```
####  Form
![Screenshot 2022-10-19 at 11 30 53](https://user-images.githubusercontent.com/1698584/196667294-900e193c-d2d8-47a2-b323-1c7ea31ccc60.png)

**Comment by rottitime** [comment]
Found a fix. Not a bug on API

**Comment by Singletoned** [comment]
Okay, good.  I was looking into this and couldn't for the life of me work out why it wasn't working
