### ISSUE TITLE
API: Direct report Learning records

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#667]
API endpoint for line managers to retrieve list of 'learning records' for direct report 

**Endpoint**
`GET /api/me/direct-report/{user-id}/learnings/`

**Response**
- Same as `GET /api/me/learnings/`.
- Support for sorting. As implemented in #573

![Screenshot 2022-10-19 at 15 00 05](https://user-images.githubusercontent.com/1698584/196712653-3ed35817-3a3d-4fd2-8715-0ca58a4adbc5.png)

**Comment by nmenezes0** [comment]
Do you also need `PATCH` and `DELETE` for this endpoint? I wouldn't have thought so - as a line manager probably wouldn't be entering/deleting learning for someone they manage.

**Comment by rottitime** [comment]
> Do you also need `PATCH` and `DELETE` for this endpoint? I wouldn't have thought so - as a line manager probably wouldn't be entering/deleting learning for someone they manage.

@nmenezes0 this will be readonly on the web, so we are good with just GET 👍🏽

**Comment by nmenezes0** [comment]
As well as the `/api/me/direct-report/<id>/learnings/` endpoint, so you also want endpoints like, `/me/direct-report/<id>/learning-social/`?

**Comment by rottitime** [comment]
> As well as the `/api/me/direct-report/<id>/learnings/` endpoint, so you also want endpoints like, `/me/direct-report/<id>/learning-social/`?

@nmenezes0 `/api/me/direct-report/<id>/learnings/` will be enough, thanks
