### ISSUE TITLE
API Report:  Staff overview

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#715]
Ticket: https://trello.com/c/dUpaUKPF/233-reports-staff-overview-tab

# Responsibility
Endpoint: 'GET /me/reports/responsibility/'

Response
```
{
    data: [
        {
            name: string //e.g. Line managers
            total_label: string //e.g. 350 (36%)
            total_value_total: number //e.g. 350
            total_value_percentage: number //e.g. 36
        }
    ]
}
```

# Grade
Endpoint: 'GET /me/reports/grade/'

Response
```
{
    data: [
        {
  name: string //e.g. Administrative Officer (AO) Equivalent
  total_label: string //e.g. 350 (36%)
  total_value_total: number //e.g. 350
  total_value_percentage: number //e.g. 36
        }
    ]
}
```

# Format

Endpoint supports following query-string values

```
format=csv // eg. csv, excel, pdf
```

**Comment by nmenezes0** [comment]
> Ticket: https://trello.com/c/dUpaUKPF/233-reports-staff-overview-tab
> 
> # Responsibility
> Endpoint: 'GET /me/reports/responsibility/'
> 
> Response
> 
> ```
> {
>     data: [
>         {
>             name: string //e.g. Line managers
>             total_label: string //e.g. 350 (36%)
>             total_value_total: number //e.g. 350
>             total_value_percentage: number //e.g. 36
>         }
>     ]
> }
> ```
> 
> # Grade
> Endpoint: 'GET /me/reports/grade/'
> 
> Response
> 
> ```
> {
>     data: [
>         {
>   name: string //e.g. Administrative Officer (AO) Equivalent
>   total_label: string //e.g. 350 (36%)
>   total_value_total: number //e.g. 350
>   total_value_percentage: number //e.g. 36
>         }
>     ]
> }
> ```
> 
> # Format
> Endpoint supports following query-string values
> 
> ```
> format=csv // eg. csv, excel, pdf
> ```
@rottitime 
Do we want to filter these users as on the skills tab e.g. by profession or business unit? I suspect we might as e.g. a head of profession would want to know the grade split for their profession alone.

**Comment by rottitime** [comment]
> > Ticket: https://trello.com/c/dUpaUKPF/233-reports-staff-overview-tab
> > # Responsibility
> > Endpoint: 'GET /me/reports/responsibility/'
> > Response
> > ```
> > {
> >     data: [
> >         {
> >             name: string //e.g. Line managers
> >             total_label: string //e.g. 350 (36%)
> >             total_value_total: number //e.g. 350
> >             total_value_percentage: number //e.g. 36
> >         }
> >     ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > # Grade
> > Endpoint: 'GET /me/reports/grade/'
> > Response
> > ```
> > {
> >     data: [
> >         {
> >   name: string //e.g. Administrative Officer (AO) Equivalent
> >   total_label: string //e.g. 350 (36%)
> >   total_value_total: number //e.g. 350
> >   total_value_percentage: number //e.g. 36
> >         }
> >     ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > # Format
> > Endpoint supports following query-string values
> > ```
> > format=csv // eg. csv, excel, pdf
> > ```
> 
> @rottitime Do we want to filter these users as on the skills tab e.g. by profession or business unit? I suspect we might as e.g. a head of profession would want to know the grade split for their profession alone.

@nmenezes0 there are no filters for this staff overview. I have attached a screenshot which just contains a export option

![image](https://user-images.githubusercontent.com/1698584/200311041-d59df1c2-4720-4c9e-a295-3724f1d52158.png)
