### ISSUE TITLE
Nginx: 404 and 500 page setup

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#752]
Configure in Nginx the below existing files as 404, and 500 error pages.

Update must be applied to all environments

- /web/out/404/index.html
- /web/out/500/index.html

**Comment by rickyp72** [comment]
@rottitime you can test in https://ellandi-temp.london.cloudapps.digital before verifying the PR
https://github.com/i-dot-ai/ellandi/pull/753
