### ISSUE TITLE
Sort out the capitalisation of the skills

### ISSUE THREAD

**Issue by nmenezes0** [i-dot-ai/ellandi#799]
Make them all sentence case for consistency, make sure we have proper capitalisation (e.g. "R" and "AWS"), remove some rogue spaces. Also ensure we're using British spellings not American eg "visualisation" or "visualization".

I think just changing stuff in here: https://github.com/i-dot-ai/ellandi/blob/develop/api/ellandi/registration/initial_data.py

**Comment by Singletoned** [comment]
Clearly we need a content designer...

**Comment by nmenezes0** [comment]
"We also need to go through and remove the duplicates as well…"
