### ISSUE TITLE
API: Invite Team Members 

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#894]
## Send request

Allow registered users send request to invite other users to Ellandi

### Request

```lang-js
POST /api/me/invites/
[
    {
      "email": "user1@example.com",
      "first_name": "string"
    },
    {
      "email": "user2@example.com",
      "first_name": "string"
    }
]
```

### Success

Status 200 for success-full invite

### Error

```lang-js
{
  "detail": "string" 
}
```

## List of invited users

Allow the user to status of members they have invited

```lang-js
GET /api/me/invites/
[
  {
    "email": "user@example.com",
    "status": "string" // "pending", "declined", "accepted"
  }
]

```

**Comment by rottitime** [comment]
@Singletoned I have taken an initial shot at this. Thinking we could submit `first_name` along with email  as this would help to personalise the email notification.

**Comment by Singletoned** [comment]
Looks good.  Two small things.  These endpoints would sit under `/api/me/` because they are tied to the current user.  And I don't think we would have a way of declining an invite, so that wouldn't be a status

**Comment by rottitime** [comment]
> These endpoints would sit under `/api/me/`

👍🏽  I have updated the description

**Comment by Singletoned** [comment]
I've updated it slightly again, basically made it a single endpoint (with a plural) that accepts and returns roughly the same thing.
