### ISSUE TITLE
Sentry. New frontend environment variable

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#914]
## Setup SENTRY_AUTH_TOKEN
SENTRY_AUTH_TOKEN

## Setup SENTRY_ENVIRONMENT
Setup `SENTRY_ENVIRONMENT` so it is available to FE as per `SENTRY_AUTH_TOKEN`

## Fix Sentry connection error

Sentry gives the following error when the browser  is posting data  to Sentry api

```
Refused to connect to 'https://o1366404.ingest.sentry.io/api/6690747/envelope/?sentry_key=0b98cc1dadb34e01b9b9be43f3c32c24&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.29.0' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by rickyp72** [comment]
manually added ENV var to `develop` to test
`cf set-env ellandi-develop NEXT_PUBLIC_ENVIRONMENT development`

**Comment by rottitime** [comment]
@rickyp72 can you add the `SENTRY_AUTH_TOKEN ` to sandbox as per the description please? 
This should fix the deployment

**Comment by rottitime** [comment]
@rickyp72  `SENTRY_AUTH_TOKEN` works fine 👍🏽 

Can you make the `SENTRY_ENVIRONMENT` available to FE same as `SENTRY_AUTH_TOKEN` is please? 
Also there is an error on connection to Sentry. I am just investigating this in meantime

**Comment by rottitime** [comment]
@rickyp72 @Singletoned there seems to be a security error 

```
Refused to connect to 'https://o1366404.ingest.sentry.io/api/6690747/envelope/?sentry_key=0b98cc1dadb34e01b9b9be43f3c32c24&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.29.0' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

Is this something you can fix as there was something similar done for fonts too? https://github.com/i-dot-ai/ellandi/blob/develop/nginx/nginx-default.conf.template

**Comment by rickyp72** [comment]
added `connect-src https://o1366404.ingest.sentry.io";` to the default.conf nginx template `nginx/nginx-default.conf.template` - This seems to have worked
